elasticsearch:
  image: polyverse/elasticsearch:9cf1e2d1ff3dec3663207b788691a29c58b82cf6
  ports:
    - "9200:9200"
kibana:
  image: kibana:4
  links:
    - elasticsearch:elasticsearch
  ports:
    - "5601:5601"
logstash:
  image: polyverse/logstash:3977e73ef4e467579af7e7a86b5c6db457b62dfd
  links:
    - elasticsearch:elasticsearch
  ports:
    - "12201:12201/udp"
    - "5000:5000"
